# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: piment.digital
description: The website of piment digital
author:
  name: Mac Oosthuizen
  email: hello@m-jo.co

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts', 'vendor',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments
