name: Piment Digital

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "bower_components", "Gemfile", "bower.json", "gulpfile.js", "package.json", "*.log"]
#include: ["robots.txt", "humans.txt", "CNAME"]
