exclude:
    - 'neat/**'
    - 'bourbon/**'

linters:
  BorderZero:
    enabled: true
  CapitalizationInSelector:
    enabled: true
  ColorKeyword:
    enabled: true
  Comment:
    enabled: true
  DuplicateProperty:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
  HexNotation:
    enabled: false
  IdWithExtraneousSelector:
    enabled: true
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: false
  PropertySortOrder:
    enabled: true
  SelectorDepth:
    enabled: true
  Shorthand:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: false
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolonAfterPropertyValue:
    enabled: true
  UnnecessaryMantissa:
    enabled: false
  UrlQuotes:
    enabled: true
  ZeroUnit:
    enabled: true
